version: '3.5'

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    volumes:
      - plexusdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - plexus-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    networks:
      - plexus-network
    depends_on:
      - elastic
    ports:
      - 5601:5601

volumes:
  plexusdata:
    name: plexusdata

networks:
  plexus-network:
    name : plexus-network
