version: '3.5'

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    volumes:
      - plexusdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - plexus-network
             
volumes:
  plexusdata:
    name: plexusdata

networks:
  plexus-network:
    name : plexus-network
